# This file was generated by GoReleaser. DO NOT EDIT.
cask "freda" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "e7aa5aa3d97d5c31347cc490ea5522b38a2dcd6596c4a1018d51c422710c6888"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec2322979ad4e782a55c4d3986c875498cfa92706d8db1479d545e05bcc38ad8"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_linux_amd64.tar.gz"
    end
  end

  name "freda"
  desc "Archive Fireflies.ai meeting transcripts to Google Cloud Storage as Markdown."
  homepage "https://github.com/agrechin/freda-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freda"

  # No zap stanza required

end
