# This file was generated by GoReleaser. DO NOT EDIT.
cask "freda" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "af8959319592faaad99691ff9924ddb21c163ee2ffff401bba70841792023013"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c3eceb222f28bd0fcfacb13937fed418ef810fcc3f07972259bc6782ff6ac89"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d4bb59fb932ceed1d647568758395842d8928defb71b6da0a0904655300b8a3"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6086c96a581e359d322e0090c79f9af32fb978bfb3a468ac10463167c8c1975"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "freda"
  desc "Archive Fireflies.ai meeting transcripts to Google Cloud Storage as Markdown."
  homepage "https://github.com/agrechin/freda-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freda"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/freda"]
    end
  end

  # No zap stanza required

end
