# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitree" do
  name "gitree"
  desc "A CLI tool that scans directories for Git repos and displays them in a tree format with status information."
  homepage "https://github.com/andreygrechin/gitree"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmd/gitree"

  on_macos do
    on_intel do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_darwin_x86_64.tar.gz"
      sha256 "632ec9bcfc9e122174b14e8decf98bc50ce7f2a55d962ff3d8f49ed3a3a52d1d"
    end
    on_arm do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_darwin_arm64.tar.gz"
      sha256 "90fa673ec71c711783dd5c87b2d93adf85cc3a7e57f68234abf4e2d9c75d77d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_linux_x86_64.tar.gz"
      sha256 "d42812aa017f1688fa1888150cb4d644b9d6aa5095fd479392d9a35aab2f4da0"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmd/gitree"]
    end
  end

  caveats do
    "As part of the installation process, brew will automatically run the following command"
    "to remove the quarantine attribute:"
    "  /usr/bin/xattr -dr com.apple.quarantine .../gitree"
  end

  # No zap stanza required
end
