# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitree" do
  name "gitree"
  desc "A CLI tool that scans directories for Git repos and displays them in a tree format with status information."
  homepage "https://github.com/andreygrechin/gitree"
  version "0.4.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmd/gitree"

  on_macos do
    on_intel do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_darwin_x86_64.tar.gz"
      sha256 "361dd5868aa6896781a91b140a5124ba4faf78ed7601c86110a0015020306d2b"
    end
    on_arm do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_darwin_arm64.tar.gz"
      sha256 "75dcf99de2e99be8c3b1a50a55e4e8711821b9704b9f95b971a6a957762eaf17"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_linux_x86_64.tar.gz"
      sha256 "5addd82e90d21c41ddd4211c181d044c0aebfd67149cc9e6dce67ed8097fc39d"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmd/gitree"]
    end
  end

  caveats do
    "As part of the installation process, brew will automatically run the following command"
    "to remove the quarantine attribute:"
    "  /usr/bin/xattr -dr com.apple.quarantine .../gitree"
  end

  # No zap stanza required
end
