# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitree" do
  name "gitree"
  desc "A CLI tool that scans directories for Git repos and displays them in a tree format with status information."
  homepage "https://github.com/andreygrechin/gitree"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmd/gitree"

  on_macos do
    on_intel do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_darwin_x86_64.tar.gz"
      sha256 "2430ea57f4603014dc24322a10492c3eb50100e74dbd0c53f5d228beed8b0c36"
    end
    on_arm do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_darwin_arm64.tar.gz"
      sha256 "49afc9c4f75ac6a14fb48bab3ade8af2761cc2baa646bf1ebcd52763132e440b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andreygrechin/gitree/releases/download/v#{version}/gitree_#{version}_linux_x86_64.tar.gz"
      sha256 "f2bc27960dfd6a9339990c00c850fe343153b50225057175c755e326c74460d7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmd/gitree"]
    end
  end

  caveats do
    "As part of the installation process, brew will automatically run the following command"
    "to remove the quarantine attribute:"
    "  /usr/bin/xattr -dr com.apple.quarantine .../gitree"
  end

  # No zap stanza required
end
