# This file was generated by GoReleaser. DO NOT EDIT.
cask "glfetcher" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2f37ff154ebc644b57f0f7b39bcb1a2a2b36ebcd0d9cfbce8a37b8421d2396bc"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7205b1ec38ba8f7321e22cc46d93b4482e203021d38be3777ddbe3489d1b6f71"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4f400c6f237061ba2e998a90037c52c91fe2171678ce85bd8c236031cc3781d"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2e5beae53b31825b367127c6d6c0a4277233305aa89fcfedd49e79372fff38f"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glfetcher"
  desc "Mirror GitLab groups into local directories."
  homepage "https://github.com/agrechin/glfetcher-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glfetcher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glfetcher"]
    end
  end

  # No zap stanza required

end
