# This file was generated by GoReleaser. DO NOT EDIT.
cask "glfetcher" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "2362d0b304067b50609b9b6c381cbc2984a5157ff3004af671ac1b00737ad75c"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "8e0361858f10078771070d941ba56935715652ff1bd4d157527d3f94046f9a0e"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "glfetcher"
  desc "Mirror GitLab groups into local directories."
  homepage "https://github.com/agrechin/glfetcher-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glfetcher"

  # No zap stanza required
end
