# This file was generated by GoReleaser. DO NOT EDIT.
cask "glfetcher" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fe8c90900652abc4c178123d048510abe3b07a010466a1b6d6fd1c9fcddf99f8"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c565ad4718c869c33ca91e2d46c880e7f44d73e90d9d4778f4eb9850dd6973e"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1daf75459731addb94dcf3806fb9163c355f4e720566092a89ccdf459c2db793"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e7dc4ec83a5a058b35bb65152eed28f1fa30e9379a894b9e3fa3343920c072d"
      url "https://github.com/agrechin/glfetcher-releases/releases/download/v#{version}/glfetcher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glfetcher"
  desc "Mirror GitLab groups into local directories."
  homepage "https://github.com/agrechin/glfetcher-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glfetcher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glfetcher"]
    end
  end

  # No zap stanza required

end
