# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssetWatcher < Formula
  desc "A command-line utility to fetch a list of IP addresses across a Google Cloud organization through Google Asset API."
  homepage "https://github.com/andreygrechin/asset-watcher"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreygrechin/asset-watcher/releases/download/v0.1.0/asset-watcher_0.1.0_darwin_x86_64.tar.gz"
      sha256 "1e705b259c49438ea55ce7d1382d337b2baf6862993058147654929301f7aaaa"

      def install
        bin.install "asset-watcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreygrechin/asset-watcher/releases/download/v0.1.0/asset-watcher_0.1.0_darwin_arm64.tar.gz"
      sha256 "1d5e7ad625156474ae1564df71fd8a3be4f4ac836614fb2d6332beabd89f3c3e"

      def install
        bin.install "asset-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/andreygrechin/asset-watcher/releases/download/v0.1.0/asset-watcher_0.1.0_linux_x86_64.tar.gz"
      sha256 "89b8ad347fbec16b63d94193155d9f0ce923726c55efe5503eeef8358d20e8fe"
      def install
        bin.install "asset-watcher"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/andreygrechin/asset-watcher/releases/download/v0.1.0/asset-watcher_0.1.0_linux_arm64.tar.gz"
      sha256 "9ed026598a7c9dd3a455c0f04cd87298b0b0e0596a155343bb6d8fd49344b9eb"
      def install
        bin.install "asset-watcher"
      end
    end
  end

  test do
    system "#{bin}/asset-watcher version"
  end
end
