# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosemver < Formula
  desc "A command-line utility and a library for validating, comparing, and manipulating semantic versions, fully adhering to the Semantic Versioning 2.0.0 specification."
  homepage "https://github.com/andreygrechin/gosemver"
  version "0.4.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta1/gosemver_0.4.0-beta1_darwin_x86_64.tar.gz"
      sha256 "553f9cf90d1f1e79f08cf89960ed5756325997067876e4b205e7be5f6338d80e"

      def install
        bin.install "gosemver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta1/gosemver_0.4.0-beta1_darwin_arm64.tar.gz"
      sha256 "9195185b46c158aee1b534927333891caa53c981221095aa373e88a3bc80dcbf"

      def install
        bin.install "gosemver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta1/gosemver_0.4.0-beta1_linux_x86_64.tar.gz"
        sha256 "1517bea1e19ad63c2f615699d2e2ca7a57636d4fe48863ae7ebbab4e0ba07833"

        def install
          bin.install "gosemver"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta1/gosemver_0.4.0-beta1_linux_arm64.tar.gz"
        sha256 "063f924caf2e2afafc6dc56e7598b34f5341974ebc34b8f3858b9e244764e249"

        def install
          bin.install "gosemver"
        end
      end
    end
  end

  test do
    system "#{bin}/gosemver version"
  end
end
