# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosemver < Formula
  desc "A command-line utility and a library for validating, comparing, and manipulating semantic versions, fully adhering to the Semantic Versioning 2.0.0 specification."
  homepage "https://github.com/andreygrechin/gosemver"
  version "0.3.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreygrechin/gosemver/releases/download/v0.3.0-beta1/gosemver_darwin_x86_64.tar.gz"
      sha256 "e9fc0eff584129a2e8eb279ae8ba9aee40dfc6f1e9817547fc37c010a1cdd9ea"

      def install
        bin.install "gosemver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreygrechin/gosemver/releases/download/v0.3.0-beta1/gosemver_darwin_arm64.tar.gz"
      sha256 "055b9f6a9bad7278841ad2e56121eb2ed4c69c1b54d57cb09026915f1b324ba8"

      def install
        bin.install "gosemver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andreygrechin/gosemver/releases/download/v0.3.0-beta1/gosemver_linux_x86_64.tar.gz"
        sha256 "de2f0d4f907073072325808447e912ca97d0a96cb8d504f71309b81839c7f7ba"

        def install
          bin.install "gosemver"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andreygrechin/gosemver/releases/download/v0.3.0-beta1/gosemver_linux_arm64.tar.gz"
        sha256 "807780b465e03204cb9dec7bc41e1c93a2ab02ce9e05220372288b368b821e5a"

        def install
          bin.install "gosemver"
        end
      end
    end
  end

  test do
    system "#{bin}/gosemver version"
  end
end
