# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosemver < Formula
  desc "A command-line utility and a library for validating, comparing, and manipulating semantic versions, fully adhering to the Semantic Versioning 2.0.0 specification."
  homepage "https://github.com/andreygrechin/gosemver"
  version "0.4.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta/gosemver_darwin_x86_64.tar.gz"
      sha256 "341bc0b07f31150ebd211756e01c27488f9532e7ee6a3671aba12d7b9742a95d"

      def install
        bin.install "gosemver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta/gosemver_darwin_arm64.tar.gz"
      sha256 "01f64d93396cde925aa0f1dbaf89b65af520e7bb12a0040ae222f0408f9c2fb6"

      def install
        bin.install "gosemver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta/gosemver_linux_x86_64.tar.gz"
        sha256 "3d6e034ca70fa71de73bae3122ba0f98e11fcfae75bb669566e8e335f4ff8504"

        def install
          bin.install "gosemver"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andreygrechin/gosemver/releases/download/v0.4.0-beta/gosemver_linux_arm64.tar.gz"
        sha256 "a4140e23b6adfa72a7c33e7e0661e037d7b4979227c655e6918f765b1f0bceb7"

        def install
          bin.install "gosemver"
        end
      end
    end
  end

  test do
    system "#{bin}/gosemver version"
  end
end
